# Generated by Django 5.0.3 on 2024-04-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_employes', '0002_appgestionemployesdepartment_and_more'),
    ]

    operations = [
    ]
