# Generated by Django 5.0.3 on 2024-04-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_employes', '0003_auto_20240405_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppGestionEmployesDepartment',
        ),
        migrations.DeleteModel(
            name='AppGestionEmployesEmployee',
        ),
    ]
